# Notes

It terns out, the design of decay pattern of espilon plays a key role here in the algorithm, under certain decay pattern, it is simply impossible to converge. The following pattern seems to have a good performance:
   
   action = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)/(i/4+1)**2)

In [32]:
import gym
import numpy as np

# Game

In [33]:
env = gym.make("FrozenLake-v0")

[2017-11-16 03:43:55,019] Making new env: FrozenLake-v0


# Model

### Constants

In [49]:
ACTIONS = [] # Action space
STATES = [] # State space
N_ACTIONS = env.action_space.n
N_STATES = env.observation_space.n
epsilon = 0.9 # Expoit v.s. Explore, this number will be updated later as the learning progress
gamma = 0.95 # Decay, same as discount for time value of money
LR = 0.8 # Learning Rate
N_GAMES = 100 #Training length
N_STEPS = 99 # How many updates each game have
lambda_= 0.9 # Eligibility Race Decay

### Q Table

In [57]:
Q = np.zeros((N_STATES, N_ACTIONS)) + 0.1

In [58]:
E = np.zeros((N_STATES, N_ACTIONS))  + 0.1# Eligibility Trace

### Act

In [59]:
def act(s,i=0):
    action = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)/np.square(i/3+1))
    return action

### Learn

In [60]:
def learn(s, a, r, s_, a_, done):
    global Q, E
    r_p = Q[s, a] # Predicted reward
    if not done:
        r_ = Q[s_, a_]
        r_t = r + gamma*r_ # Target reward
    else:
        r_t = r
        
    error = r_t - r_p
    
    E[s, :] *= 0
    E[s, a] = 1
    
    Q = Q * LR * error * E  
    E *= gamma*lambda_
    print(Q)
    return Q

# Session

In [61]:
for i in range(N_GAMES):
    s = env.reset()
    a = act(s,i)
    for j in range(N_STEPS):
        #env.render()       
        s_, r, done, _ = env.step(a)       
        a_ = act(s_, i)
        _ = learn(s, a, r, s_, a_, done)
        s = s_
        a = a_
        if done:
            break
    

[[ -4.00000000e-04  -0.00000000e+00  -0.00000000e+00  -0.00000000e+00]
 [ -4.00000000e-05  -4.00000000e-05  -4.00000000e-05  -4.00000000e-05]
 [ -4.00000000e-05  -4.00000000e-05  -4.00000000e-05  -4.00000000e-05]
 [ -4.00000000e-05  -4.00000000e-05  -4.00000000e-05  -4.00000000e-05]
 [ -4.00000000e-05  -4.00000000e-05  -4.00000000e-05  -4.00000000e-05]
 [ -4.00000000e-05  -4.00000000e-05  -4.00000000e-05  -4.00000000e-05]
 [ -4.00000000e-05  -4.00000000e-05  -4.00000000e-05  -4.00000000e-05]
 [ -4.00000000e-05  -4.00000000e-05  -4.00000000e-05  -4.00000000e-05]
 [ -4.00000000e-05  -4.00000000e-05  -4.00000000e-05  -4.00000000e-05]
 [ -4.00000000e-05  -4.00000000e-05  -4.00000000e-05  -4.00000000e-05]
 [ -4.00000000e-05  -4.00000000e-05  -4.00000000e-05  -4.00000000e-05]
 [ -4.00000000e-05  -4.00000000e-05  -4.00000000e-05  -4.00000000e-05]
 [ -4.00000000e-05  -4.00000000e-05  -4.00000000e-05  -4.00000000e-05]
 [ -4.00000000e-05  -4.00000000e-05  -4.00000000e-05  -4.00000000e-05]
 [ -4.

 [-0. -0. -0. -0.]]
[[-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]]
[[-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]]
[[-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]]
[[-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0

[[-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]]
[[-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]]
[[-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]]
[[-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0. -0. -0.]
 [-0. -0.

In [62]:
Q

array([[-0., -0., -0., -0.],
       [-0., -0., -0., -0.],
       [-0., -0., -0., -0.],
       [-0., -0., -0., -0.],
       [-0., -0., -0., -0.],
       [-0., -0., -0., -0.],
       [-0., -0., -0., -0.],
       [-0., -0., -0., -0.],
       [-0., -0., -0., -0.],
       [-0., -0., -0., -0.],
       [-0., -0., -0., -0.],
       [-0., -0., -0., -0.],
       [-0., -0., -0., -0.],
       [-0., -0., -0., -0.],
       [-0., -0., -0., -0.],
       [-0., -0., -0., -0.]])

# Valuation

In [63]:
rewards = []
for i in range(100):
    s = env.reset()    
    for j in range(N_STEPS):
        
        a  = np.argmax(Q[s])
        s_, r, done, _ = env.step(a)
        #env.render()
        s = s_
        if done:         
            break
    rewards.append(r)
np.mean(rewards)

0.0